# -*- coding: utf-8 -*-
"""library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Id0FXJGVrcAsVgf_zWhsBIpOXJZmqCJT
"""

!pip install mxnet
!pip install gluonnlp pandas tqdm
!pip install sentencepiece
!pip install transformers==3.0.2
!pip install torch
!pip install sklearn
!pip install git+https://git@github.com/SKTBrain/KoBERT.git@master