# -*- coding: utf-8 -*-
"""math.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pnug0rN3Fz2TyHm_3locTKmm57L00nja
"""

test_size = 0.3
random_state = 7
max_len = 64
batch_size = 64
warmup_ratio = 0.1
num_epochs = 15
max_grad_norm = 1
log_interval = 200
learning_rate =  3e-6

